# Generated by Django 5.2.dev20240823160747 on 2024-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('specialized', models.CharField(max_length=255)),
                ('takeaway', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('outdoor', models.BooleanField(default=False)),
                ('smoking_area', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['restaurant_name', 'category', '-rating'],
            },
        ),
    ]
