# Generated by Django 5.1.1 on 2024-10-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
