# Generated by Django 5.1.1 on 2024-10-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewentry',
            name='image',
        ),
    ]
