# Generated by Django 5.1.2 on 2024-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('restaurant_name', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('specialized', models.TextField(blank=True, null=True)),
                ('takeaway', models.BooleanField(blank=True, null=True)),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('outdoor', models.BooleanField(blank=True, null=True)),
                ('smoking_area', models.BooleanField(blank=True, null=True)),
                ('wifi', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
