# Generated by Django 5.1.2 on 2024-10-15 04:50

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "data.json")

class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data)
    ]
