# Generated by Django 5.1 on 2024-10-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_auto_20241015_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('fish', 'Fish'), ('lamb', 'Lamb'), ('other', 'Other'), ('pork', 'Pork'), ('rib_eye', 'Rib Eye'), ('sirloin', 'Sirloin'), ('t_bone', 'T-Bone'), ('tenderloin', 'Tenderloin'), ('wagyu', 'Wagyu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='city',
            field=models.CharField(blank=True, choices=[('central_jakarta', 'Central Jakarta'), ('east_jakarta', 'East Jakarta'), ('north_jakarta', 'North Jakarta'), ('south_jakarta', 'South Jakarta'), ('west_jakarta', 'West Jakarta')], max_length=50, null=True),
        ),
    ]
