# Generated by Django 5.1.2 on 2024-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_alter_menu_category_alter_menu_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='specialized',
            field=models.CharField(blank=True, choices=[('argentinian', 'Argentinian'), ('brazilian', 'Brazilian'), ('breakfast_cafe', 'Breakfast Cafe'), ('british', 'British'), ('french', 'French'), ('fushioned', 'Fushioned'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('local', 'Local'), ('local_westerned', 'Local Westerned'), ('mexican', 'Mexican'), ('western', 'Western'), ('singaporean', 'Singaporean')], max_length=50, null=True),
        ),
    ]
