# Generated by Django 5.1.2 on 2024-10-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_auto_20241015_1150'),
        ('spinthewheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='explore.menu'),
        ),
        migrations.AddField(
            model_name='option',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SpinHistory',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
